---
openapi: 3.0.0

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: v1
  title: Team Lithium API
  description: |
    The first version of the testing

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
servers:
  - url: http://localhost:1001
    description: Localhost

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Patients
  - name: Doctors



################################################################################
#                                   Parameters                                 #
################################################################################

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /registerDocter:
    post:
      security:
        - bearerAuth: []
      description: Register a Doctor
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hospitalID:
                  type: integer
                doctorID:
                  type: string
      responses:
        '200':
          description: OK
  /login:
    post:
      description: Get all patients data.
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        '400':
          description: Bad request. User ID must be an integer and larger than 0.

  /patients/_all:
    get:
      tags:
        - Patients
      description: Get all patients data.
      responses:
        200:
          description: All Patients object
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/Patient'

  /patient/{patient-id}:
    parameters:
      - $ref: '#/parameters/patient-id'
    get:
      security:
        - bearerAuth: []
      tags:
        - Patients
      description: Get basic information about a patient.
      responses:
        200:
          description: The patient object
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/Patient'


################################################################################
#                                 Definitions                                  #
################################################################################
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    token:
      type: object
      properties:
        accessToken:
          type: string
    Doctor:
      title: A Slack message
      type: object
      properties:
        address:
          type: string
          description: Message text
        age:
          type: string
          description: Message text
        docType:
          type: string
          description: Message text
        firstName:
          type: string
          description: Message text
        lastName:
          type: string
          description: Message text
    Patient:
      title: A Slack message
      type: object
      properties:
        address:
          type: string
          description: Message text
        age:
          type: string
          description: Message text
        docType:
          type: string
          description: Message text
        firstName:
          type: string
          description: Message text
        lastName:
          type: string
          description: Message text

    credentials:
      title: A Slack message
      type: object
      properties:
        username:
          type: string
          description: Message text
        password:
          type: string
          description: Message text
      required:
        - username
        - password
